// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// sonar_negloglik_cpp
double sonar_negloglik_cpp(NumericVector x, NumericMatrix u, NumericVector N, NumericMatrix w, NumericMatrix y, int spot);
RcppExport SEXP _SONAR_sonar_negloglik_cpp(SEXP xSEXP, SEXP uSEXP, SEXP NSEXP, SEXP wSEXP, SEXP ySEXP, SEXP spotSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type u(uSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type N(NSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type w(wSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type spot(spotSEXP);
    rcpp_result_gen = Rcpp::wrap(sonar_negloglik_cpp(x, u, N, w, y, spot));
    return rcpp_result_gen;
END_RCPP
}
// sonar_grad_cpp
NumericVector sonar_grad_cpp(NumericVector x, NumericMatrix u, NumericVector N, NumericMatrix w, NumericMatrix y, int spot);
RcppExport SEXP _SONAR_sonar_grad_cpp(SEXP xSEXP, SEXP uSEXP, SEXP NSEXP, SEXP wSEXP, SEXP ySEXP, SEXP spotSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type u(uSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type N(NSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type w(wSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type spot(spotSEXP);
    rcpp_result_gen = Rcpp::wrap(sonar_grad_cpp(x, u, N, w, y, spot));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SONAR_sonar_negloglik_cpp", (DL_FUNC) &_SONAR_sonar_negloglik_cpp, 6},
    {"_SONAR_sonar_grad_cpp", (DL_FUNC) &_SONAR_sonar_grad_cpp, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_SONAR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
