# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sonar_negloglik_cpp <- function(x, u, N, w, y, spot) {
    .Call(`_SONAR_sonar_negloglik_cpp`, x, u, N, w, y, spot)
}

sonar_grad_cpp <- function(x, u, N, w, y, spot) {
    .Call(`_SONAR_sonar_grad_cpp`, x, u, N, w, y, spot)
}

